### ISSUE TITLE
Unable to run plugin on Netbeans 12.0 with Oracle JDK 11.0.6

### ISSUE THREAD

**Issue by BxN2** [matthiasblaesing/netbeans-mantis-integration#38]
Hi,
as the title mentions, the problem was in running the plugin on Java platform higher than 1.8.
Plugin crashed because of ClassNotFound for JAXBException etc...
I was able to resolve the problem by adding this dependency to pom.xml:

<dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.4.0-b180830.0359</version>
</dependency>
Bye!

**Comment by BxN2** [comment]
I can push the solution if you want to the new branch.

**Comment by matthiasblaesing** [comment]
Its not that easy, master already has the necessary changes, but also more. I have just not yet found the time to rebuild the plugin.

**Comment by matthiasblaesing** [comment]
I updated the plugin, please test: https://plugins.netbeans.apache.org/catalogue/?id=44

**Comment by BxN2** [comment]
Hi,

now  I don't get an Exception but it still doesn't work.

I get message: "Colud not create repository".


Le 6.7.2020. à 18:19, Matthias Bläsing a écrit :

**Comment by matthiasblaesing** [comment]
Please provide the message log: http://wiki.netbeans.org/FaqLogMessagesFile

**Comment by BxN2** [comment]
After repeating the installation procedure to note the log, it started 
to work :-)

Thank you!

**Comment by matthiasblaesing** [comment]
Thank you for testing.
